name: 'Deploy files to OSS'
description: 'GitHub Action to deploy static files to OSS'
inputs:
  oss-endpoint:
    description: 'Endpoint of access over Internet (required if ossutil is not configured)'
    required: false
    default: ''
  oss-accesskey-id:
    description: 'AccessKey ID of user with write access to OSS (required if ossutil is not configured)'
    required: false
    default: ''
  oss-accesskey-secret:
    description: 'AccessKey secret of the user identified by the previous AccessKey ID (required if ossutil is not configured)'
    required: false
    default: ''
  oss-sts-token:
    description: 'STS token (required only if using STS and ossutil is not configured)'
    required: false
    default: ''
  oss-path:
    description: 'Path to the location you wish to deploy files to, i.e. oss://<BUCKET NAME>/<PATH>'
    required: true
  local-path:
    description: 'Local path to files for deployment (absolute path or relative path to workspace)'
    required: false
    default: '.'
  ignored-patterns:
    description: 'Blob patterns of files to ignore in deployment'
    required: false
    default: '.git*'
  delete-first:
    description: 'Whether to delete files in the specified location before deployment'
    required: false
    default: 'false'
  force-setup-ossutil:
    description: 'Whether to force download and configure ossutil'
    required: false
    default: 'false'
  debug:
    description: 'Whether to enable debug logging'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/bin/deploy.sh
      shell: bash
      env:
        OSS_ENDPOINT: ${{ inputs.oss-endpoint }}
        OSS_ACCESSKEY_ID: ${{ inputs.oss-accesskey-id }}
        OSS_ACCESSKEY_SECRET: ${{ inputs.oss-accesskey-secret }}
        OSS_STS_TOKEN: ${{ inputs.oss-sts-token }}
        OSS_PATH: ${{ inputs.oss-path }}
        LOCAL_PATH: ${{ inputs.local-path }}
        IGNORED_PATTERNS: ${{ inputs.ignored-patterns }}
        DELETE_FIRST: ${{ inputs.delete-first }}
        FORCE_SETUP_OSSUTIL: ${{ inputs.force-setup-ossutil }}
        DEBUG: ${{ inputs.DEBUG }}
        OSSUTIL_DOWNLOAD_URL: https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64
