name: 'OSS Deployment Action'
author: 'Yang Hanlin'
description: 'GitHub Action to deploy static files to Aliyun (Alibaba Cloud) OSS'

inputs:
  oss-endpoint:
    description: 'OSS endpoint (required if ossutil is not pre-configured)'
    required: false
    default: ''
  oss-accesskey-id:
    description: 'AccessKey ID of user with write access to OSS (required if ossutil is not pre-configured)'
    required: false
    default: ''
  oss-accesskey-secret:
    description: 'AccessKey secret of the user identified by the previous AccessKey ID (required if ossutil is not pre-configured)'
    required: false
    default: ''
  oss-sts-token:
    description: 'STS token (required only if using STS and ossutil is not pre-configured)'
    required: false
    default: ''
  oss-path:
    description: 'Path to the location you''d like to deploy files to, i.e. oss://<BUCKET NAME>/<PATH>'
    required: true
  local-path:
    description: 'Path to the location you''d like to deploy files from'
    required: false
    default: '.'
  ignored-patterns:
    description: 'Blob patterns of files (separated by spaces) to ignore in deployment'
    required: false
    default: '.git'
  delete-first:
    description: 'Whether to delete files under `oss-path` before deployment'
    required: false
    default: 'false'
  force-setup-ossutil:
    description: 'Whether to force download and configure even if ossutil is pre-configured'
    required: false
    default: 'false'
  cache-ossutil:
    description: 'Whether to cache downloaded ossutil'
    required: false
    default: 'false'
  debug:
    description: 'Whether to enable debug logging'
    required: false
    default: 'false'
  ossutil-version-:
    description: 'Version of ossutil to download if none is found in PATH; this input parameter is undocumented and NOT guaranteed to be stable'
    required: false
    default: '1.7.15'

runs:
  using: 'composite'
  steps:
    - name: Run script to prepare variables
      run: "'${{ github.action_path }}/bin/prepare-variables.sh'"
      shell: bash
      id: prepare-variables
      env:
        OSSUTIL_VERSION: ${{ inputs.ossutil-version- }}
        DEBUG: ${{ inputs.debug }}
    - name: Set up cache
      uses: actions/cache@v3
      if: inputs.cache-ossutil == 'true'
      with:
        path: ${{ steps.prepare-variables.outputs.workspace }}
        key: ${{ steps.prepare-variables.outputs.cache-key }}
    - name: Run script to deploy
      run: "'${{ github.action_path }}/bin/deploy.sh'"
      shell: bash
      env:
        OSS_ENDPOINT: ${{ inputs.oss-endpoint }}
        OSS_ACCESSKEY_ID: ${{ inputs.oss-accesskey-id }}
        OSS_ACCESSKEY_SECRET: ${{ inputs.oss-accesskey-secret }}
        OSS_STS_TOKEN: ${{ inputs.oss-sts-token }}
        OSS_PATH: ${{ inputs.oss-path }}
        LOCAL_PATH: ${{ inputs.local-path }}
        IGNORED_PATTERNS: ${{ inputs.ignored-patterns }}
        DELETE_FIRST: ${{ inputs.delete-first }}
        FORCE_SETUP_OSSUTIL: ${{ inputs.force-setup-ossutil }}
        DEBUG: ${{ inputs.DEBUG }}
        WORKSPACE: ${{ steps.prepare-variables.outputs.workspace }}
        OS_TYPE: ${{ steps.prepare-variables.outputs.os-type }}
        OSSUTIL_SPEC: ${{ steps.prepare-variables.outputs.ossutil-spec }}
        OSSUTIL_DOWNLOAD_URL: ${{ steps.prepare-variables.outputs.ossutil-download-url }}

branding:
  color: orange
  icon: upload-cloud
