name: 'Deploy files to OSS'
description: 'GitHub Action to deploy static files to OSS'
inputs:
  oss-endpoint:
    description: 'Endpoint of access over Internet'
    required: true
  oss-path:
    description: 'Path to the location you wish to deploy files to, i.e. oss://<BUCKET NAME>/<PATH>'
    required: true
  oss-accesskey-id:
    description: 'AccessKey ID of user with write access to OSS'
    required: true
  oss-accesskey-secret:
    description: 'AccessKey secret of the user identified by the previous AccessKey ID'
    required: true
  local-path:
    description: 'Local path to files for deployment'
    required: true
  ignored-patterns:
    description: 'Patterns of files to ignore in deployment; default to .git*'
    required: false
    default: '.git*'
  delete-first:
    description: '(⚠ CAUTION) Whether to delete files in the specified location before deployment; default to false'
    required: false
    default: false
  internal-ossutil-download-url:
    description: '(🔒 INTERNAL) URL to download ossutil'
    required: false
    default: 'http://gosspublic.alicdn.com/ossutil/1.6.19/ossutil64'
  internal-ossutil-workspace:
    description: '(🔒 INTERNAL) Path to workspace of ossutil which contains the credentials and other files'
    required: false
    default: '~/ossutil'
runs:
  using: 'composite'
  steps:
    - run: 'echo This GitHub Action is currently under construction.'
